apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: py-GitHub-quay 
  janus-idp.io/tekton: py-GitHub-quay
  backstage.io/kubernetes-id: py-GitHub-quay
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: py-GitHub-quay
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  